### ISSUE TITLE
401 Unauthorized without further information on OIDC login

### ISSUE THREAD

**Issue by TBG-FR** [sdoxsee/cats-nest#17]
Hello there !

Some time ago I followed your (**awesome**) article, to implement OIDC authentication in a NestJS app, but sometimes when I log myself in, I get on a `{"statusCode":401,"message":"Unauthorized"}` page. Nothing appears in NestJS logs, nothing else on the web page.

I'm hence creating this issue, so we can (hopefully) find the cause and solve it, all together 😄 

I tried adding log lines in your code to find where it was stopping, and the last one appears before https://github.com/sdoxsee/cats-nest/blob/ed28bc6bddca5c8f8cde3b4f67c3b5ffa58c893c/back-end/src/auth/login.guard.ts#L8 , that's the only clue I have for now

**Comment by sdoxsee** [comment]
Thanks for the issue. I haven't experienced this myself so please keep this updated as you learn more. Thanks!

**Comment by TBG-FR** [comment]
Something I found really strange, is that it doesn't happen when I use https://oidctest.wsweet.org/ but very frequently with another private provider... I'll keep digging !

**Comment by TBG-FR** [comment]
As I was suspecting it, the issue comes from the provider side (I managed to get more info by modifying some lib code, see https://github.com/nestjs/passport/pull/502 )

Do you have any idea on how we could improve the error management (modifying your example code and/or lib code) ? Not displaying the `{
  "statusCode": 401,
  "message": "Unauthorized ..."
}` page but redirecting to a page of our choice ? This would be a great improvement 😄

**Comment by TBG-FR** [comment]
As I was suspecting it, the issue comes from the provider side (I managed to get more info by modifying some lib code, see https://github.com/nestjs/passport/pull/841 )

Do you have any idea on how we could improve the error management (modifying your example code and/or lib code) ? Not displaying the `{
  "statusCode": 401,
  "message": "Unauthorized ..."
}` page but redirecting to a page of our choice ? This would be a great improvement 😄

**Comment by TBG-FR** [comment]
> As I was suspecting it, the issue comes from the provider side (I managed to get more info by modifying some lib code, see [nestjs/passport#841](https://github.com/nestjs/passport/pull/841) )
> 
> Do you have any idea on how we could improve the error management (modifying your example code and/or lib code) ? Not displaying the `{ "statusCode": 401, "message": "Unauthorized ..." }` page but redirecting to a page of our choice ? This would be a great improvement 😄

The right way to do it seems to be [Exception Filters](https://docs.nestjs.com/exception-filters) ! Closing this issue then ;)

**Comment by sdoxsee** [comment]
Thanks for the updates @TBG-FR
