### ISSUE TITLE
Refresh token is undefined

### ISSUE THREAD

**Issue by edwardchanjw** [sdoxsee/cats-nest#6]
Do you know any other openid connect implementation with nest.js and passport?

```
  async validate(tokenset: TokenSet): Promise<any> {
    const userinfo: UserinfoResponse = await this.client.userinfo(tokenset);

    try {
      const id_token = tokenset.id_token
      const access_token = tokenset.access_token
      const refresh_token = tokenset.refresh_token
      const user = {
        id_token,
        access_token,
        refresh_token,
        userinfo,
      }
      console.log(user)
```

**Comment by sdoxsee** [comment]
Are you requesting the offline_access scope?

**Comment by edwardchanjw** [comment]
Other than setup scope to offline_access?

I am new to openid, Any pointer of article can I read to setup properly. Mostly on [Authenticate responce](https://openid.net/specs/openid-connect-core-1_0.html#AuthResponse). On this repo cats_nets's setup it is the /callback right?

I am getting tired, might fall asleep. Thanks ahead of any guidance. Thanks

**Comment by sdoxsee** [comment]
If your openid-connect provider (e.g. google) is openid-connect compliant, you'll need to add "offline_access" to your list of requested scopes if you want to get a refresh token.

i.e. change the following environment variable from the blog post
```OAUTH2_CLIENT_REGISTRATION_LOGIN_SCOPE=openid profile```
to
```OAUTH2_CLIENT_REGISTRATION_LOGIN_SCOPE=openid profile offline_access```

**Comment by edwardchanjw** [comment]
Thanks, sound good for me right now. 
If I got time then I have time to write article on the different flow over oauth2 and open id connect, passport.js abstract a bit little much. Anyway, great article for openid-connect on node.js.

Because on OAuth2 having this normally like in this [Link](https://www.loginradius.com/engineering/blog/google-authentication-with-nodejs-and-passportjs/). But Openid-connect, I am still feeling I missing some piece.

```
app.get('/auth/google', 
  passport.authenticate('google', { scope : ['profile', 'email'] }));
 
app.get('/auth/google/callback', 
  passport.authenticate('google', { failureRedirect: '/error' }),
  function(req, res) {
```
